version: '3'
services:
  mlflow:
    image: mlflow
    build: .
    ports:
      - "172.31.37.200:5000:5000"
    volumes:
      - ./mlruns:/mlruns
    command: mlflow server --host 0.0.0.0 --port 5000

  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile-airflow
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - PYTHONPATH=/opt/airflow/dags
      - MLFLOW_TRACKING_URI=http://172.31.37.200:5000
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./datasets:/opt/airflow/datasets  # Add this line
    ports:
      - "172.31.37.200:8080:8000"
    command: bash -c "
      airflow db init &&
      airflow users create --username admin --firstname Admin --lastname User --role Admin --password admin --email admin@example.com &&
      airflow db upgrade &&
      airflow webserver
      "
    depends_on:
      - postgres
      - mlflow

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile-airflow
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - PYTHONPATH=/opt/airflow/dags
      - MLFLOW_TRACKING_URI=http://172.31.37.200:5000
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./datasets:/opt/airflow/datasets  # Add this line
    command: bash -c "airflow db upgrade && airflow scheduler"
    depends_on:
      - postgres
      - airflow-webserver
      - mlflow

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

volumes:
  postgres-db-volume: