FROM apache/airflow:2.6.3-python3.9

USER root

# Install system dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER airflow

# Install Python packages
COPY requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt

# Set the PYTHONPATH
ENV PYTHONPATH=/opt/airflow/dags

# Set the MLflow tracking URI
ENV MLFLOW_TRACKING_URI=http://mlflow:5000