FROM apache/airflow:2.5.1

USER root

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

USER airflow

# Install MLflow and any other required packages
RUN pip install --no-cache-dir mlflow boto3 pandas scikit-learn numpy matplotlib seaborn scipy apache-airflow psycopg2-binary acryl-datahub[airflow] sagemaker